force-app/main/default/objects/Customer_Success_Story__c/Customer_Success_Story__c.object-meta.xml
<CustomObject>
    <label>Customer Success Story</label>
    <nameField>
        <label>Customer Success Stories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Success Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Success_Story__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Success_Story__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Customer_Success_Cascade_Helper.cls
public class Customer_Success_Cascade_Helper {
    
    public static void RatingRank(List<Customer_Success_Story__c> CssList)
    {
        List<Customer_Success_Story__c> allStories =  [Select Name, Rating__c From Customer_Success_Story__c Order by Rating__c DESC];
        Integer Rank;
        for (Integer i = 1; i <= allStories.size();i++)
            allStories[i-1].Rank__c = i; 
        
        update(allStories);
    }

}