force-app/main/default/objects/Product2/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Determines the owner of the product.</description>
    <label>Product Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>Installation and repair orders</description>
    <label>Work Order</label>
    <nameField>
        <label>Work Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contacts</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NewWork.cls
public class NewWork {
    public static void createNewOrder(List<OrderItem> orderList) 
    {
        List<OrderItem> ProductList = [SELECT Id,Order.AccountId,Product2.Contact__c From OrderItem
                                      Where id in :orderList And Product2.Contact__c != Null];
        List<Work_Order__c> OrdersToInsert = new List<Work_Order__c>();
        for (OrderItem oi : ProductList)
        {
            Work_Order__c Order2Add = new Work_Order__c();
            Order2Add.Name = 'Assigned to the Product Owner';
            Order2Add.Contact__c = oi.Product2.Contact__c;
            Order2Add.Account__c = oi.Order.AccountId;
            OrdersToInsert.add(Order2Add);             
        }
        insert OrdersToInsert;
     }
}